### ISSUE TITLE
[EPIC] ⚙️ Dashboard base components

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#11026]
## ⚙️ Summary

Build the components which will be used to construct the new dashboards. For the most part, these components should be very simple and only used on the Dashboard. I just want to break them down like this to ensure the dashboards are consistent.

## 🎨 Design File

https://www.figma.com/design/oZhQe9ahidHFfaiqgREvxa/Dashboard-(All-users)?node-id=1010-18639&t=TY7PrKKdMPrt00fN-0

### 🧑‍🎨 Designer

@substrae 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

## Subcomponents

```[tasklist]
### Tasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11031
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11078
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11075
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/11077
```

**Comment by yonikid15** [comment]
The Accordion task shouldn't be done within the component, but in the parent. The `useLocalStorage` hook allows us to store a key with a list of the accordion id(s) that are open. The using that we can set the default open/closed state of the accordions.

Thanks @esizer for helping me out with this :1st_place_medal:
