### ISSUE TITLE
✨ Admin / Users / Profile - Update tab content

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#11485]
## ✨ Feature

Standardize tab to include reusable components of candidate information.

URLS
- `admin/users/..ID../profile`
- `admin/users/..ID..` **redirects to** `.../profile`

## 🕵️ Details

[Link to figma file](https://www.figma.com/design/vZEg5z6aXiJPNB07LamrgY/Admin---Users?node-id=387-8202&t=hFJ3OC5t5O5a1DSC-1) by @Jerryescandon 

[Clickable prototype](https://www.figma.com/proto/vZEg5z6aXiJPNB07LamrgY/Admin---Users?node-id=710-40974&t=bv1oObGsTQIWYxsB-1&scaling=scale-down-width&content-scaling=fixed&page-id=387%3A8202)

### ☑️ To-do

- [x] Update Title to show name
- [ ] Update subtitle to say 'Applicant profile'
- [x] Add breadcrumbs
- [x] Update table of contents
- [x] Move print button underneath table of contents
- [ ] Update applicant information section using reusable info components
 
## 📸 Compare screenshots

![Image](https://github.com/user-attachments/assets/2a61cf46-b9bf-4435-89dd-0f9359010a35)

![Image](https://github.com/user-attachments/assets/49d77b6b-7599-4be6-954b-59d7b87fbeea)

## 🛑 Blockers

```[tasklist]
### Blocked By
```

**Comment by Jerryescandon** [comment]
Most of this work was done by Eric invertedly, there's new tickets for the missing stuff.
