### ISSUE TITLE
Allow Users query to be filtered by email, name, or phone number

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#2812]
## Description

Add an optional filter to the paginated Users query which allows for filtering by email, name or phone number.

This is to support the table filter shown [here](https://www.figma.com/proto/XS4Ag6GWcgdq2dBlLzBkay/Admin-v3-(Profile-release)?node-id=465%3A8698&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=410%3A1984&show-proto-sidebar=1)

![screenshot](https://user-images.githubusercontent.com/4313717/169162746-1c9382b4-cbd2-4203-9e47-04d27ede14f7.png)

## Acceptance Criteria
- [x] email, name, phone number, or a general search field are optional filters that can be applied to users and usersPaginated queries
- [x] The different fields should act as an AND filter (eg only return users that match the email AND the phone number)
- [x] the "general" search field should work as an orWhere query, applied to email, firstName, lastName, and phoneNumber
- [x] a phpunit test for this

## Todo
- [ ] How to deal with firstName/lastName db fields vs single name search field?

**Comment by tristan-orourke** [comment]
Some thoughts on the name field
- Split the search term by space, and run an orWhere query that applies to all name segments, and both firstName and lastName
- Is it possible to run some kind of includes query on the database? Does the search term include  the substring in the database? But then we'd want to run the includes query in the other direction at the same time - does the db name contain a the search term as a substring?
