### ISSUE TITLE
Put description meta text in our html index pages

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#3086]
### talentsearch
**English**: GC Digital Talent is the new recruitment platform for digital and tech jobs in the Government of Canada. Apply now!
**French**: Talent numérique du GC est la nouvelle plateforme de recrutement pour les emplois numériques et technologiques au gouvernement du Canada. Postulez maintenant!

### indigenousapprenticeship
**English**: Apply now to get started on your IT career journey.
**French**: Postulez dès aujourd'hui pour entamer votre parcours de carrière en TI.

### admin
**English**: Recruit and manage IT employees in the Government of Canada.
**French**: Recruter et gérer des employés en TI au gouvernement du Canada.

## To Do
- [x] confirm app-level copy -- @gobyrne 
- [x] update `frontend/admin/public/index.html`
- [x] update `frontend/talentsearch/public/index.html`
- [x] update `frontend/indigenousapprenticeship/public/index.html`
- [x] Use react-helmet to set the description in the root page components, based on current language.

**Comment by mnigh** [comment]
#3156 will need to be resolved in order for French copy to be switched to.

**Comment by patcon** [comment]
options brought up on grooming:
1. react-helment
2. apache-level htaccess re-org to use index_en.html and index_fr.html

(2) might be quick, but agreement was that (1) is better. And react-helmet is popular and will help us with other things.

**Comment by MCommonda** [comment]
English "Apply now to get started on you IT career journey." 
French: " Postulez dès aujourd'hui pout entamer votre parcours de carrière en TI. ''

**Comment by gobyrne** [comment]
Ok, copy is in. Ready to go
