### ISSUE TITLE
Migrate to new IMTD server VM (PHP8.x and nginx migration)

### ISSUE THREAD

**Issue by patcon** [GCTC-NTGC/gc-digital-talent#3560]
<sup>ℹ️ [Figma (root)][figma] | [Sitemap][sitemap]</sup>
<sup>_This initial comment is collaborative and open to modification by all._</sup>

Related:
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/1472
- https://github.com/GCTC-NTGC/gc-digital-talent/pull/3559

## Description
We are currently on php7 and using apache on IMTD VMs. We're basically mirroring this in docker images.

IMTD's next VM base image is php8.x, but uses nginx as webserver. There is different setup for this, since not only does nginx have its own config language, but it also interfaces quite differently with php, via FastCGI of the php-fpm variant.

Given the moving pieces involved, it might make sense to create a new Dockerfile for this migration, instead of trying to edit the old one and having the PR linger until 100%ready. This way, we can merge this work prior to officially migrating the UAT/prod servers, which might require time.

For example:
- we could rename the current php-container to `infrastructure/php-container/apache.Dockerfile` and create a new one called `nginx.Dockerfile` or `new.Dockerfile`.
- we could use [docker-compose profiles](https://docs.docker.com/compose/profiles/) to ensure this new Dockerfile doesn't launch by default.
- we could copy the smoke test and just run it on mainline (as opposed to every commit like we do the other smoke test), to ensure the nginx docker container stays working even before we're using it

This way, when it comes time to get deploy working with the new prod/uat image (with nginx), we'll have the config tested and ready. And then when we want to use the new nginx setup locally, it will simple be a matter of fiddling with the docker-compose profile, and deleting the old `apache.Dockerfile`.

## Proposed To Do
- [ ] find out specs of IMTD VM image ([debian <=> ubuntu compat chart](https://askubuntu.com/a/445496/232907))
  - PHP version: 
  - nginx version: 
  - linux distro & version: 
- [ ] intermediary step: migrate all .htaccess into single apache.conf (nginx has no analog of htaccess)
    - potentially related https://github.com/GCTC-NTGC/gc-digital-talent/issues/3571#issuecomment-1205631004
- [ ] migrate base image from `php:7.4-apache` to [`php:8.x-apache`](https://hub.docker.com/_/php/#:~:text=php%3A%3Cversion%3E%2Dapache)
  - [ ] unit and e2e tests pass
- [ ] migrate base image from `php:8.x-apache` to [`php:8.x-fpm`](https://hub.docker.com/_/php/#:~:text=Apache%20configuration%20options.-,php%3A%3Cversion%3E%2Dfpm,-This%20variant%20contains) + nginx
  - [ ] transpose apache conf into nginx https://github.com/GCTC-NTGC/gc-digital-talent/issues/1647
- [ ] get deploy process with nginx image on UAT
- [ ] set docker-compose profile so that local dev uses nginx image
- [ ] get deploy process with nginx image on prod

## Acceptance Criteria
- [ ] ...

   [image]: https://user-images.githubusercontent.com/305339/166570935-6425a615-82c7-4b2f-9840-5c7d698fa2ab.png
   [image-link]: https://example.com
   [figma]: https://go.talent.c4nada.ca/figma
   [sitemap]: https://go.talent.c4nada.ca/sitemap
