### ISSUE TITLE
Learn More pages (Storybook, light mode)

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#4024]
There are some Learn More pages associated with the homepage.

Acceptance criteria:
- [ ] Files are in the talentsearch workspace in a directory and file structure that conform to the style guide
- [ ] All strings are in localized strings
- [ ] Storybook stories in English and French
- [ ] Chromatic snapshots in desktop and mobile sizes
- [ ] Coding style conforms to the style guide and our best practices
- [ ] Matches design in desktop and mobile sizes
- [ ] Design review from designers
- [ ] Update homepage "Learn more" section content and images 
    - REF: https://github.com/GCTC-NTGC/gc-digital-talent/pull/4049#discussion_r981391128

Out of scope:
- [ ] Dark mode activation happens in #4028
- [ ] Routing to be able to navigate to the page happens in #4026
- [ ] Translation happens in #4025

**Comment by JoshBeveridge** [comment]
For context, the learn more pages at the bottom of the homepage link to the following:
- OCIO section: OCIO's TBS site page
- DCMO section: DCMO's TBS site page
- Concept to code section: the TC Report main page
- 
As a result, there isn't any work here in terms of creating new pages on our app.

**Comment by tristan-orourke** [comment]
@JoshBeveridge what about Women in Tech and Pride in STEM?

**Comment by JoshBeveridge** [comment]
@tristan-orourke those are a part of #4096

**Comment by tristan-orourke** [comment]
If we don't have to build the Learn More pages, just link to existing pages, I think this issue can be closed!
