### ISSUE TITLE
Teams and Roles

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4360]
We will add a Teams entity, which Users can be a part of, and each Pool must belong to.

We will implement new Roles and Permissions based Policies, using the [Laratrust](https://laratrust.santigarcor.me/docs/7.x) library, which allows for roles to be assigned only in the context of a certain team. This way, some permissions/roles may be specific to resources associated with a certain team, and some may be universal.

Initially, we will implement a basic set of roles, defined in [this table](https://docs.google.com/spreadsheets/d/1RC7wufxwjLEvaEunHsfZfOzBefg218dvvzkDwKSiQjI/edit?usp=sharing)/

We will also update the Admin UI so that users will only see the resources they have access to, and can work with the Team entity.

### Figma

[Wireframe](https://www.figma.com/file/UsrB15yicgDCLDQmx3snyl/User-Flows?node-id=0%3A1&t=AI1pm7V8jWMDSwjK-0)

### Users > Edit User

![image](https://user-images.githubusercontent.com/16977254/203607426-25b533f4-38eb-4efd-835d-07ba5e5ad011.png)

### Manage membership (FROM EDIT USER)

![image](https://user-images.githubusercontent.com/16977254/203608836-07ec1f59-adaa-4fa5-b2a8-f412b3c99d40.png)

### Organizations

![image](https://user-images.githubusercontent.com/16977254/203607577-f1df458c-b598-4ac6-9cb6-c17ae71f5747.png)

### Organizations > Edit (or New)

![image](https://user-images.githubusercontent.com/16977254/203607911-8b1bc83b-1f3b-4cb0-ac60-33c4e9d7bb1b.png)

### Organizations > (org) > View

![image](https://user-images.githubusercontent.com/16977254/203608296-5d87f8c8-10dd-42dd-bd27-75714495f730.png)

### Manage membership (FROM VIEW ORG)

![image](https://user-images.githubusercontent.com/16977254/203609504-e7f0ae51-f9aa-434b-9cb0-5949151dc0f3.png)

### Remove Membership 

![image](https://user-images.githubusercontent.com/16977254/203609832-9b042f0e-68e1-42d0-9f93-87c9b93872d7.png)

**Comment by tristan-orourke** [comment]
Steps to implementing this
- [ ] Install Laratrust, run migrations
- [ ] Add Talent Org to backend, tied to Laratrust Team, and one default org tied to all existing pools.
- [ ] Seed/initialize permissions and roles
- [ ] Script or migration(?) to assign appropriate role to all existing users, including correct team
- [ ] Rewrite policies to check permissions instead of simple role
- [ ] Rewrite frontend role checks to either be aware of new role or use a new mechanism https://github.com/gctc-ntgc/gc-digital-talent/issues/4040#issuecomment-1377739396 (blocked by question)
- [ ] Build admin ui for modifying user roles, connect to api
- [ ] Ensure pools are attached to a team when they are created (blocked by questions - how?)
- [ ] Big remaining questions:
    - [ ] Existing admins can see all users, all requests, all pools, etc. Even if we change the policies, how to we update the UI so people are only shown the correct items/pages?
    - [ ] Do we need to update the api to get this to work?
