### ISSUE TITLE
Support Indigenous Languages - Phase 1

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#4620]
We currently have translations for the IAP Homepage in several indigenous languages. We also want to have infrastructure in enable these languages on any page of the site, if translated. 

[Figma Prototype](https://www.figma.com/proto/tUuPyWzaZWSEwCflpfOLq6/IAP-Homepage---V3.5.2?page-id=0%3A1&node-id=803%3A625&viewport=-5833%2C2071%2C0.5&scaling=min-zoom&starting-point-node-id=117%3A1358)

![IAP Language Picker.png](https://images.zenhubusercontent.com/5d9ded8fd25901000101f3f0/8c10c582-acfc-4aef-9c2e-13ad06e4a40e)

## Acceptance Criteria
- [x] Language switcher appears at top of IAP page
- [x] Provided translations are each moved into a json file with correct ids.
- [x] All language between header and footer changes with language switcher.
- [x] This does not yet need to change our normal english-french translation workflow (in terms of the scripts we run)
- [ ] Selecting a language in the language picker links you to the page in the correct language code.
- [ ] When we guess locale in LanguageRedirectProvider, check for indigenous language code stored at a different key in localStorage. Fallback on the bilingual language if it doesn't exist.
- [ ] Switch language code in meta tag

**Comment by mnigh** [comment]
@tristan-orourke can this epic issue be closed now that all the related issues (9 of 9) have been completed?

**Comment by petertgiles** [comment]
Agreed that epic is done.
