### ISSUE TITLE
DESIGN EPIC - Minimum Lovable Product  (MLP)

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4704]
# EPIC DESCRIPTION

What kind of features and updates do we need to design and build for a polished version of the MVP.
The MLP should aim to be a polished basic functionality that works smoothly and seamlessly. It should include both DCM and IAP considerations

It should pass both usability and accessibility tests.

## DESIGNS NEEDED 🎨 

IAP considerations:
- #4703 
- #4705 
- #4706
- #4708 
- #4709 
- #4711 

### Application process redesign
- [ ] Polished application process (break steps apart)
- [ ] Editable education requirement on job poster and validation on application
- [ ] Language requirement validation on application
- [ ] Review non-job poster skills on application (allowed? how to present to application reviewers?)
- [ ] Copy cleanup: (experience forms, Term / Indeterminate / Permanent)
- [ ] Multi page process (Talent Cloud style)^
- [ ] "Stepper" feature

### Application profile redesign
  - [ ] "Add new experience" single button, then allow users to choose from multiple experience types that are defined.
  - Experience types: Provide information in card-format before user opens the form.
- Experience and skills: Add examples for users showing how skills could be filled out. 
- [ ] Remove Role and salary (do we need it? per application?)
- [ ] Dashboard or landing page instead of bringing the user directly to their profile. This page should provide the user with notifications and allow them to view their current profile, pools they've applied to, and more.
- Pool specific privacy settings (I want to be considered-not for this pool)
  - Remove status box from profile

### DCMO Admin improvements
- Admin - change status for all pools at once
- Consolidate all filters on admin pages

### Search Redesign
- Talent Search (polish and add dynamic disclosure of results)

### Skill Picker ( #4874 )
- Skill picker component: add more robust filtering & sorting options like sort alphabetically, by relevance (e.g., application based, classification, etc.), and multi select. (See skills picker section for examples)

### Others
- Nudges for improving quality and number of applications (DCM IT-05 400 baker candidates)
- Accessibility audit of all pages
- Fable testing on all user facing pages
- Some analytics tracked in Azure
- Dark Mode enabled!

Dev Considerations (ONLY GRAY INPUT SO FAR)
- Test full site recovery
- Migrate to NGINX server
- Translation Management System
- More security auth work (PKCE)
- Internal authentication
- New roles and orgs

**Comment by gobyrne** [comment]
This is stale. Closing
