### ISSUE TITLE
⌨ Replace copy on IAP logo image with `h1` HTML element

### ISSUE THREAD

**Issue by MaddyDaigle** [GCTC-NTGC/gc-digital-talent#4719]
## Description
Permanent solution to issue #4718.

## TODO
- [x] confirm how this is going to react on devices with the IAP team, and whether we need to import the unique font used in the logo first (@BrookeCameron and @MCommonda)

## Screenshot of Issue
<img width="738" alt="Screen Shot 2022-11-10 at 5 14 46 PM" src="https://user-images.githubusercontent.com/1794660/201219321-5551a72d-aa34-42b3-96a7-7832db7b8b07.png">

## Acceptance Criteria
- [ ] Remove the [image of text](https://www.w3.org/TR/UNDERSTANDING-WCAG20/visual-audio-contrast-text-presentation.html) for the IAP logo & associated text.  
- [ ] Make "IT Apprenticeship Program for Indigenous Peoples" regular text and an `<h1>` (since there isn't one currently on the page). 
- [ ] Make "Apply today to get started on your IT career journey" regular text.

**Comment by MaddyDaigle** [comment]
Hey @BrookeCameron and @MCommonda! I finally had the time to post the accessibility issue on the IAP page with the logo.  I remember you mentioned this might not be able to be changed to regular text that users can resize.  Please advise. :)

**Comment by mnigh** [comment]
We have [translations of the logo text](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4587#issuecomment-1343410963) back for the four languages currently being worked on!

@BrookeCameron unless this issue (to convert the copy on the logo to plain text) will be worked on right away, would you be able to create svgs for crg, crk, ojw, mic based on translated text that we received? I'd be happy to work on it with you, if you'd like.

**Comment by substrae** [comment]
We _can_ make this real text, but we need to know a few things (@MCommonda):
- Does it have to retain the branded font used by the current image?
  - If yes, what font is being used, and do we have a web license for it?
  - If no, easy-peasy, we just size our current font (Open Sans) to match the logo as it is now

In terms of execution, we'll just detach the graphic from the type, and reposition to match using an `<h1>` and subtitle element.

**Comment by Jerryescandon** [comment]
Icon only SVG file

![ESDC IT Apprenticeship Program Logo Icon Only White_ Icon Only White](https://user-images.githubusercontent.com/16977254/233711854-e978c2cb-809a-4c1f-890f-27a38c3ccf5c.svg)

**Comment by BrookeCameron** [comment]
We have confirmed with the IAP team that this can in fact be converted to our font in Open Sans. 🎉
