### ISSUE TITLE
⚙️ Buttons - in progress

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#4802]
# ⚙️ Summary

### [Visit the Figma file](https://www.figma.com/file/T1R64oNWog10OXiBnuiMkz/GC-Digital-Talent-Design-Standards?node-id=91%3A1167&t=Y3EgcEG2nkC1kNNI-1)

A component that acts as a standard element for taking action. This button component represents the visual button style of an element, not the functional HTML `<button>` element. This means that the button component should handle the styling for both `<button>` and `<a>` when they are designed and implemented as visual buttons.

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**

## ✅ Design checklist
- [x] Default component
- [ ] Dark mode component
- [x] Component variants
- [x] Dark mode component variants (if applicable)
- [x] Foundational design info (e.g. color info, icons, helpful values)
- [x] Mobile (`base` query) layout and space diagram
- [x] Desktop (`p-tablet` query or larger) layout and space diagram
- [ ] Accessibility considerations
- [x] Hover states (if applicable)
- [x] Dark mode hover states (if applicable)
- [x] Focus states (if applicable)
- [x] Dark mode focus states (if applicable)

## ✅ Accessibility checklist
- [x] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [x] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [x] Non-standard states or interactions have been described and provided accessible design context

# 🛠️ Properties

## [PROPERTY NAME]

[PROPERTY DESCRIPTION]

[PROPERTY SCREENSHOT(S)]

# 💡 Interaction states

[SUMMARY CONTENT]

## Hover

[HOVER DESCRIPTION]

[HOVER SCREENSHOT]

## Focus

[FOCUS DESCRIPTION]

[FOCUS SCREENSHOT]

# 🥰 Accessibility

## [ACCESSIBILITY FEATURE]

[FEATURE DESCRIPTION]

**Comment by substrae** [comment]
@MaddyDaigle @RM-1978 Content wise I think this is pretty solid now, but I would very much like any insight you can provide - specifically on interaction states. I've already done a AA contrast check as well, but feel free to run another.
