### ISSUE TITLE
⚙️ Text input component

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#4832]
# ⚙️ Summary

### [Visit the Figma file]()

[PURPOSE AND DESCRIPTION]

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**

## ✅ Design checklist
- [ ] Default component
- [ ] Dark mode component
- [ ] Component variants
- [ ] Dark mode component variants (if applicable)
- [ ] Foundational design info (e.g. color info, icons, helpful values)
- [ ] Mobile (`base` query) layout and space diagram
- [ ] Desktop (`p-tablet` query or larger) layout and space diagram
- [ ] Accessibility considerations
- [ ] Hover states (if applicable)
- [ ] Dark mode hover states (if applicable)
- [ ] Focus states (if applicable)
- [ ] Dark mode focus states (if applicable)

## ✅ Accessibility checklist
- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

# 🛠️ Properties

## [PROPERTY NAME]

[PROPERTY DESCRIPTION]

[PROPERTY SCREENSHOT(S)]

# 💡 Interaction states

[SUMMARY CONTENT]

## Hover

[HOVER DESCRIPTION]

[HOVER SCREENSHOT]

## Focus

[FOCUS DESCRIPTION]

[FOCUS SCREENSHOT]

# 🥰 Accessibility

## [ACCESSIBILITY FEATURE]

[FEATURE DESCRIPTION]

**Comment by gobyrne** [comment]
@mnigh can we close this now?
