### ISSUE TITLE
⚙️ Skill picker

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#4874]
# ⚙️ Summary

The skill picker is a complex interaction that helps users identity which skills (from our list) is relevant for their interaction, this component is commonly paired up with the Skill in detail component to attach relevant context to a user's (applicant) skill selection, the following are the common places a skill picker will be used:

- Applicants use this component in the profile section to fill out which skills they have and are relevant to their work experience
- Applicants use this component during the application process to add the requested skills (on the poster) to their profile, and then they use the Skills in detail component to justify their skill selection
- Managers use this component to specify the skillset that the ideal candidate would have for the job they are offering
- Pool managers use this to specify on the job poster the essential and asset skills that will be assessed during the recruitment process

### Current concerns:
- Skill picker paired with Skills in detail during Profile creation is overwhelming (30 skills)
- Keyboard trap (on dropdown): https://github.com/GCTC-NTGC/gc-digital-talent/issues/4794
- Keyboard trap (on list): https://github.com/GCTC-NTGC/gc-digital-talent/issues/4761
- Skill picker is irrelevant during applications
- Unrelated skills (neither essential nor asset)  poster skills are relevant to users during applications but not to Managers (how do we reconcile?)

### Keyboard trap options for 4761
- Make sure the user can EXIT the section:
   - Make it a list (option 1)
   - Make it a table (option 2)
   - Bring pagination back (option 3)

```
 Jump to the End of the List
Once in the list, you can press , to get out of the list. If list wasn't tagged correctly, the user would be forced to press tab or ctrl+down arrow continuously to get to the end of the list. This is frustrating when the list is long.
```

### [Visit the Figma file]()

[PURPOSE AND DESCRIPTION]

**For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.**

## ✅ Design checklist
- [ ] Default component
- [ ] Dark mode component
- [ ] Component variants
- [ ] Dark mode component variants (if applicable)
- [ ] Foundational design info (e.g. color info, icons, helpful values)
- [ ] Mobile (`base` query) layout and space diagram
- [ ] Desktop (`p-tablet` query or larger) layout and space diagram
- [ ] Accessibility considerations
- [ ] Hover states (if applicable)
- [ ] Dark mode hover states (if applicable)
- [ ] Focus states (if applicable)
- [ ] Dark mode focus states (if applicable)

## ✅ Accessibility checklist
- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

# 🛠️ Properties

## [PROPERTY NAME]

[PROPERTY DESCRIPTION]

[PROPERTY SCREENSHOT(S)]

# 💡 Interaction states

[SUMMARY CONTENT]

## Hover

[HOVER DESCRIPTION]

[HOVER SCREENSHOT]

## Focus

[FOCUS DESCRIPTION]

[FOCUS SCREENSHOT]

# 🥰 Accessibility

## [ACCESSIBILITY FEATURE]

[FEATURE DESCRIPTION]

**Comment by mnigh** [comment]
@Jerryescandon can this issue be closed since the only issue in the epic has been completed?
