### ISSUE TITLE
Ongoing/passive pool recruitment

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#4918]
# 🌩️ Summary

DCM has requested an urgent addition to the pool setup that adds a new persistent section to the browse page. This section will feature pools for each and every work stream/classification combination and act as passive recruitment for talent. Each pool will have 1 or 2 essential skills at the most, and will feature a list of asset skills associated to that combination.

These pools will run for around 6 months, by which point we will have decided how to handle their expiry based on the "Outstanding concerns" section below. The reason they expire is threefold:
- To allow DCM to artificially limit submissions by withholding the ability to apply when there is an overabundance of talent
- To allow applicants to try again in regular intervals if they fail to meet acceptance criteria
- To allow DCM to update the acceptance criteria as the work streams evolve in a fair way

## Files and resources
- [Copy and translations](https://1drv.ms/x/s!Ajx0PiLIqEzSgclLBHqj1QfQ_ZeU4A?e=uVaP3l) (WIP)

## Screenshot

![Browse jobs - Ongoing recruitment](https://user-images.githubusercontent.com/6960386/203999529-a9f7ff62-2166-4d61-a5a4-134538954616.png)

# 🧩 Requirements
- [ ] The removal of the existing "No jobs posted" card
- [ ] The ability for DCM to produce a pool for each work stream/classification combination and apply an expiry of 6 months
- [ ] UI on the browse page that organizes these specific pools into work stream accordions, in order of seniority
  - [ ] The accordions themselves should be ordered to match the [Careers in digital - Information technology](https://www.canada.ca/en/government/system/digital-government/gcdigital-community/careers-digital.html) list (alpha order)
- [ ] The ability for candidates to apply to each pool via the "Apply to level" button
- [ ] The ability to quickly filter the list by selecting a work stream from a dropdown above the list - nothing fancy happening here, just hide the accordions that aren't the option they've selected
- [ ] A flag on the pool model to indicate that these posters are ongoing recruitment
  - [ ] Allows us to modify the job poster (see below) ever so slightly for added context

## Job poster context

Because ongoing recruitment will have slight administrative differences for candidates, we need to alter the context accordion at the top of the poster to provide comparable information about how ongoing recruitment works.

![image](https://user-images.githubusercontent.com/6960386/204003292-41ee125d-a80b-4084-b411-660605c596a9.png)

# 🙀 Nice-to-haves

## Status indicators

- Paused (shows up when the pool expires)
  - The current design accounts for a "why" link here, but we can omit this for now and worry about it closer to an expiry period
  - Functionally, this why link will trigger a dialog with content, so if it's easy enough to set up, great
- Application submitted (shows when the user has submitted an application but hasn't been accepted/rejected)
- Successfully accepted (shows when the user has been accepted)
- Re-apply (shows when the user has been rejected)
- Continue application (shows when the user has an existing application to this pool, linking them there)

![image](https://user-images.githubusercontent.com/6960386/204377592-5b83c048-0887-4999-88a3-3367b863a7bd.png)

## Recommended based on your skills

![image](https://user-images.githubusercontent.com/6960386/203998554-cff0812c-12d3-4b76-a369-65538f29c406.png)

While this UI can launch without this feature, it would be useful for candidates who are logged in and already have a profile to be shown whether or not a particular essential skill has already been met inside of a work stream. If any of the essential skills on the 4 work stream posters are met by the candidate, this badge would show up on the accordion, and the accordion would be brought to the top of the list.

## Next recruitment estimate

Because these pools will all run for a fixed 6 month period, it would be helpful to either hard code a "next recruitment" date or calculate the launch of the following pool so that users have an idea of when they can apply again. This would replace the "Check back" status described above.

![image](https://user-images.githubusercontent.com/6960386/204377811-dfe061a0-fdd2-4bcd-8504-03b6c6106518.png)

## Pool distinction based on DCM breakdown

DCM [has a concrete breakdown of how IT work streams should be divided](https://www.canada.ca/en/government/system/digital-government/gcdigital-community/careers-digital.html). Ideally, the pools should reflect this division to make their work easier in terms of placing candidates. As it stands, this breakdown would require model rework to accommodate the cross between work stream, job type, and classification level.

All work streams contain the following combinations:
- Technician / IT-01
- Analyst / IT-02
- Lead / IT-03
- Advisor / IT-03
- Manager / IT-04
- Senior advisor / IT-04

![image](https://user-images.githubusercontent.com/6960386/203998667-80a1a1df-4bac-41f1-b926-f6eb473dfb6d.png)

# 💡 Outstanding concerns
- These pools will show up alongside the existing "migration" pools we've created in search - this has been deemed not a problem for now and will be addressed later
- Once the first round of pools expire and a second wave has been created by DCM, the way they show up in the admin UI is going to get super confusing
- Once a second/third/etc. wave has been created, we need to consider how these pools show up in search, because theoretically, managers should be requesting from an aggregate ongoing list, as opposed to each iteration of the same pool
- We're not sure how replacing these pools in the UI is going to work when the time comes - we'll likely have to create:
  - New UI for admins to manage ongoing recruitment separately from active pool recruitment
  - A new category of pool as opposed to a simple flag
- The job poster and application process for these ongoing recruitments needs to be streamlined ASAP, because it should be easier than a regular pool in terms of application effort and time
- When it comes time to consider "Orgs" we'll need to decide if ongoing recruitment is restricted to DCM or not

# 📑 Related issues
- #4952 
- #4935
- #4934
- #4933
- #4931
- #4930
