### ISSUE TITLE
Address issues raised by security scan

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5000]
Address all issues raised in report resulting form 2022/12/01 security scan.

[AZ-14360 - GC Talent - uat-talentcloud.tbs-sct.gc.ca ADMIN PAGE 2022.12.01 Security Report.pdf](https://github.com/GCTC-NTGC/gc-digital-talent/files/10144063/AZ-14360.-.GC.Talent.-.uat-talentcloud.tbs-sct.gc.ca.ADMIN.PAGE.2022.12.01.Security.Report.pdf)

## High Severity Issues
- [x] API Mass Assignment
    - A false positive. Our graphql API ignores all fields of the post request besides `query`, `operationName` and `variables`.
- [x] #5001

## Medium Severity Issues
- [x] #5002

## Low Severity Issues
- [ ] Cacheable SSL Pages found - add `Cache-Control: no-cache` or `Cache-Control: no-store` header to application pages.
    - resolved for our index pages recently in #4925
    - I believe we can justify caching our resource (js/css) files because we have cache-busting hashes in filenames
    - QUESTION: #4925 does not add no-cache header to tc-report pages; should we do that, or should we justify allowing those to be cached?
- [x] #5036
    - Our only two externally loaded resources are Google Fonts and Google Analytics.  Both of these return dynamically updated content and so cannot be reliably hashed for SRI.
- [x] #5184
- [x] #5186
- [x] Improper Access to Lotus Domino Administration Databases
    - This is a false positive. We do not have .NSF files or a Domino server

**Comment by mnigh** [comment]
@tristan-orourke can this epic issue be closed or does https://github.com/GCTC-NTGC/gc-digital-talent/issues/9967 need to be added to it?
