### ISSUE TITLE
♻️ Remove deprecated graphql fields entirely

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5137]
Find all the fields which have been marked as `@deprecated` in the schema, and remove them from the backend entirely.
Some of these fields are computed, in which case its an Accessor which must be deleted.
In other cases, an entire database column can be dropped.
When removing a field, must also delete...
   - corresponding Inputs in schema
   - corresponding fields in Factory classes
   - instances of that field in tests
   - references in class methods (accessors, scopes, filter methods)

# Acceptance Criteria
1. [ ] Survey all the deprecated fields and decide if any should be kept around for now, for any reason
2. [ ] Delete deprecated fields in schema
3. [ ] Delete related fields in schema Inputs
4. [ ] Drop related columns from database
5. [ ] Remove related accessors in Eloquent classes
6. [ ] Remove references to field in tests
7. [ ] Remove field in Factory classes
8. [ ] _Seek out and destroy_ 🚀 💥  any remaining references to these fields in any other code.

**Comment by petertgiles** [comment]
I wonder if we should close this and instead focus on targeted issues like #5290.   This would make a good issue template though.

**Comment by petertgiles** [comment]
Maybe a spike?

**Comment by petertgiles** [comment]
Current deprecated fields:

user.languageAbility
user.isIndigenous
user.wouldAcceptTemporary
applicant.languageAbility
applicant.isIndigenous
applicant.wouldAcceptTemporary
pool.status  #4183
applicantfilter.wouldAcceptTemporary
query.countPoolCandidates
query.lastestPoolCandidateSearchRequests

**Comment by mnigh** [comment]
Current deprecated graphql queries and fields:

## queries

### `applicant`
- entire query

### `applicants`
- entire query

### `applicantFilter`
- entire query

### `applicantFilters`
- entire query

### `latestPoolCandidateSearchRequests`
- entire query

### `poolCandidates`
- entire query

### `poolCandidateFilter`
- entire query

### `poolCandidateFilters`
- entire query

### `poolCandidateSearchRequests`
- entire query

### `user`
- user.languageAbility
- user.isIndigenous
- user.expectedSalary (#6226)
- user.expectedClassifications (#6226)
- user.wouldAcceptTemporary
- user.pools
- user.expectedGenericJobTitles (#7645)

### `users`
- entire query

## types
### `ApplicantFilter`
- ApplicantFilter.wouldAcceptTemporary

**Comment by tristan-orourke** [comment]
Closing the epic, since the two remaining tickets are easy enough to track on their own.
