### ISSUE TITLE
Applicant dashboard

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#5685]
## ✨ Description and goal

In order to provide applicants with a better profile management experience, as well as to provide them with a better overview of their data on the platform, we're introducing a new "home base" UI called the dashboard that has the primary goal of summarizing the user's profile information, their resume, and their recruitment information. By doing so, they're provided with an at-a-glance perspective of how complete their profile is, while giving them fast access to problem areas that require their attention.

## 🎨 Design File

<details>
  <summary><strong>📸 Screenshot: full dashboard</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219750843-7f488839-6ef5-4cea-8117-c617856087be.png" />
</details>

Figma file: https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Profile-dashboard?node-id=310%3A4163

Status table: https://docs.google.com/spreadsheets/d/16OjYysdlrsSP8IrQJLL7UXYzPA6iskJnlRzeMQ8gDJc/edit#gid=0

### Routing

Proposed URL: `/dashboard`

This page will functionally replace the "My applications" page and thus can replace it in the navigation.

Because this represents the new home for logged-in applicants, this page should be the first place they are presented with post-login. In a similar fashion, when a user first registers for the platform, after they've completed the onboarding form, they should be brought here. In both cases, if the user is arriving from an "Apply now" button, they should be brought back to that application process instead.

### Hero area

The hero area consists of two (eventually three) blocks that each summarize and provide access to the user's profile information and their skills and experience information. Each card's title should link to the respective pages, while in the case of the profile information, each section should link directly to the appropriate edit form. Sections that have errors or are missing required information are highlighted in red, while completed sections receive a checkmark. This creates a sense of completion as the user progresses through providing the information.

<details>
  <summary><strong>📸 Screenshot: hero area with data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219753807-63359e47-c591-40f3-b14e-e9111daadbe5.png" />
</details>

<details>
  <summary><strong>📸 Screenshot: hero area without data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219753936-7a5321a9-bc4e-4655-ae41-ab59a42cf5ff.png" />
</details>

### Application area

The application area reproduces the functionality lost on the "My applications" page and updates its look and feel. It takes advantage of the existing status data model to categorize applications into three categories:
- Draft applications
- Submitted applications
- Application history

Each section is an expand/collapse element, with the first two categories expanded by default. The draft applications section is unique in that it provides a link to the opportunities page as a prompt to create new applications.

Based on the existing status data framework for applications, the following statuses should translate to the UI as described below.

<details>
  <summary><strong>🚨 Categorizing and displaying statuses</strong></summary>
  <pre><code>status                        | UI category            | UI text
-----------------------------------------------------------------------------------
draft                         | draft applications     | continue this application
new application               | submitted applications | application received
application under review      | submitted applications | under review
screen in (available)         | submitted applications | pending skills assessment
under assessment              | submitted applications | assessment in progress
draft expired                 | application history    | submission date has passed
screened out (on application) | application history    | screened out
screened out (on assessment)  | application history    | screened out
qualified (available)         | application history    | qualified
qualified (unavailable)       | application history    | qualified
qualified (withdrew)          | application history    | qualified
placed casual                 | application history    | qualified
placed term                   | application history    | qualified
placed indeterminate          | application history    | qualified
expired                       | application history    | qualified
removed                       | application history    | qualified</code></pre>
</details>

<details>
  <summary><strong>📸 Screenshot: application area with data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219754125-c699ed79-c187-4a7a-9a5d-83da2567ad40.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: application area without data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219754251-1ac83325-956c-4fe5-9468-2f7bab0ba0a8.png" />
</details>

### Recruitment area

<details>
  <summary><strong>📸  Screenshot: recruitment area with data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219754433-38684a37-4b68-4712-ae9a-7e0dbfdcef3c.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: expired recruitment card</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219755518-e09be87c-074f-48b6-acb6-ed0a202978bb.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: placed recruitment card</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219755737-35199c0c-36c0-48a1-a19a-6c3191e4c6b7.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: removing availability dialog</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217918116-678fa41f-0f03-4610-b75c-4402d80d4939.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: adding availability dialog</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/217918205-55d53a50-23e8-4db1-9527-99fa45fa64c9.png" />
</details>

<details>
  <summary><strong>📸  Screenshot: recruitment area without data</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219754674-c915876c-1fe6-4492-84ae-b48ace048bcd.png" />
</details>

### Resulting changes to the existing profile

The dashboard causes a few changes that required to the existing profile page to help with cohesiveness and clarity:
- Remove the "status" section and ensure its removal doesn't impact candidate and admin functionality
- Remove the "My pools" section
- Remove the "My skills and experience" section
- Update the "On this page" sidebar to reflect section completion, matching the hero area of the dashboard

<details>
  <summary><strong>📸  Screenshot: full updated profile</strong></summary>
  <img src="https://user-images.githubusercontent.com/6960386/219754840-562e8d9e-8541-41c2-b4a2-c8b39d5198bd.png"/>
</details>

## 🌎 Localization

English copy can be found in the Figma file, happy to move it over somewhere else if the need arises.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

### Routing
- [ ] When the user registers for the first time and completes the introductory form, they are brought to this new UI unless they are registering through an application to an opportunity, in which case they should be directed back to that application
- [ ] When the user logs in, they are brought to this new UI unless they are coming through an application to an opportunity, in which case they should be directed back to that application

### Hero area
- [ ] When viewing the page, the user's profile sections display whether they are complete or not
- [ ] When viewing the page, the user's experiences are summarized by type
- [ ] When clicking on the "My profile information"/"View" link, the user is taken to a modified profile UI where they can manage their profile information
- [ ] When clicking on a profile section, the user is brought directly to that section's edit page.
- [ ] When clicking on the "My resume and experiences"/"View" link, the user is taken to the Skills and experience UI

### Application area
- [ ] The "My applications" section accurately displays the user's applications according to the status criteria outlined above
- [ ] The "Draft applications" and "Submitted applications" expand/collapse elements are expanded by default and collapse when the title or chevron is clicked
- [ ] Clicking the "Start a new application by browsing available opportunities" link takes the user to the Browse opportunities UI
- [ ] The "Application history" expand/collapse element is collapsed by default and expands when the title or chevron is clicked
- [ ] Each section shows the appropriate null state if no data is present
- [ ] Clicking on an application's "See job ad" link takes the user to the appropriate job poster page
- [ ] Clicking on an application's "Get support" link triggers the user's configured email client with the relevant recruitment administrator's email address populated
- [ ] Draft applications show a "Delete this application" link that, when clicked, triggers a dialog asking the user to confirm their decision to delete the application
- [ ] All other applications show a "View my application link that, when clicked, takes the user to the summary of their application

### Recruitment area
- [ ] The "My qualified recruitments" section accurately displays the user's currently qualified recruitment processes and categorizes them based on whether the recruitment is actively being hired from or expired
- [ ] The "Active recruitments" expand/collapse element is expanded by default and collapses when the title or chevron is clicked
- [ ] The "Expired recruitments" expand/collapse element is collapsed by default and expands when the title or chevron is clicked
- [ ] Each section shows the appropriate null state if no data is present
- [ ] Each recruitment accurately shows the user's current "availability" status along with a link, that when clicked, triggers a modal asking them if they'd like to change their status
- [ ] If the user's status is set to unavailable, they do not appear in manager search results for that specific recruitment and are shown to DCM administrators as unavailable in that process
- [ ] Clicking on a recruitment's "See job ad" link takes the user to the appropriate job poster page
- [ ] Clicking on a recruitment's "View my application" link takes the user to the summary of their application to that recruitment
- [ ] Clicking on a recruitment's "Get support" link triggers the user's configured email client with the relevant recruitment administrator's email address populated

### Changes to the profile
- [ ] The profile no longer contains a "My status" section
- [ ] The applicant can still successfully apply to opportunities despite "My status" being removed
- [ ] Recruitment administrators can still effectively view, manage, qualify, and refer applicants despite "My status" being removed and no refer to the "availability" offered at the per-recruitment level on the dashboard
- [ ] The "My pools" section has been removed and users can now view their applications and recruitments on the dashboard
- [ ] The "My skills and experience" section has been removed and users can now view their resume information via the dashboard hero area
- [ ] The "On this page" sidebar showcases completion status of each section and matches the look and feel of the dashboard profile summary in the hero area

## ⚙️ Related issues
- TBD

**Comment by tristan-orourke** [comment]
> `draft expired                 | submitted applications | submission date has passed`

Should `draft expired` be in the application history section instead? They were never actually submitted.

**Comment by substrae** [comment]
You are correct, sir! Good catch!

**Comment by brindasasi** [comment]
@substrae  could you provide a mock up for Application History card ?

**Comment by substrae** [comment]
@brindasasi Done! :D

**Comment by substrae** [comment]
Just want to note a few changes @tristan-orourke @brindasasi 
- I've updated most of the boxed, non-card content to use the existing "well" component (the visuals are being updated slightly as a part of #5430 )
- The hero area has been updated to be clearer and provide added context for when optional information can be filled out
- I've added an extra state for recruitments that accounts for when a user has been placed in a job

**Comment by mnigh** [comment]
@substrae 16 of 16 issues completed in this epic: is it ok to close as completed?

**Comment by substrae** [comment]
@mnigh

Assuming the issues covered all the acceptance criteria, yep!
