### ISSUE TITLE
♻️ Clean up schema

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#5778]
## ♻️ Debt/Refactor

After completing spikes #2365 and #2266, we should be able to reduce some duplication in our API schema, and improve how relationships are protected with field level directives.

## 🕵️ Details

This is a collection of tasks we might want to do

```[tasklist]
- [x] ~Reduce duplication between User and Applicant roles (see #4362 for discussion). Can Applicant be simply removed, now that we have field level permissions?~ decided to go in a different direction
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6106
- [ ] #4362
- [x] Add field-level permissions to PoolCandidate type (notes, user, pool)
- [x] Add field-level permissions to ApplicantFIlter (skills, pools)
- [x] Add field-level permissions to PoolCandidateFilter (pools) -> or can we just deprecate+remove PoolCandiateFilter? (#5193?)
- [x] Add field-level permissions to Skill type (experiences)
- [x] ~Use field-level permissions on inputs to combine updateUserAsUser and updateUserAsAdmin? (undecided on value of this)~ see #9149
- [ ] #5193
- [x] ~Can we improve how we guard collections of items in the schema? [Discussion #6038](https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6038)~ We've decided to lean into authorizedToView scope, canOnParent to restrict access to collection fields entirely.
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/4635
```

**Comment by mnigh** [comment]
4 of 4 Issues completed, but the tasks section of the issue description has a bunch of stuff unresolved. are we still planning to do any of these things? if so, they should have issues created for each one. also, if so, do they need to be part of this epic? if not, can we close this issue epic as completed? @GCTC-NTGC/developers, thoughts?

- Reduce duplication between User and Applicant roles (see #4362 for discussion). Can Applicant be simply removed, now that we have field level permissions?
- Add field-level permissions to PoolCandidate type (notes, user, pool)
- Add field-level permissions to ApplicantFIlter (skills, pools)
- Add field-level permissions to PoolCandidateFilter (pools) -> or can we just deprecate+remove PoolCandiateFilter? (#5193?)
- Add field-level permissions to Skill type (experiences)
- Use field-level permissions on inputs to combine updateUserAsUser and updateUserAsAdmin? (undecided on value of this)
- Can we improve how we guard collections of items in the schema? [Discussion #6038](https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6038)

**Comment by mnigh** [comment]
> 4 of 4 Issues completed, but the tasks section of the issue description has a bunch of stuff unresolved. are we still planning to do any of these things? if so, they should have issues created for each one. also, if so, do they need to be part of this epic? if not, can we close this issue epic as completed? @GCTC-NTGC/developers, thoughts?
> 
> * Reduce duplication between User and Applicant roles (see [♻️ Only `me` query should return the entire User object #4362](https://github.com/GCTC-NTGC/gc-digital-talent/issues/4362) for discussion). Can Applicant be simply removed, now that we have field level permissions?
> * Add field-level permissions to PoolCandidate type (notes, user, pool)
> * Add field-level permissions to ApplicantFIlter (skills, pools)
> * Add field-level permissions to PoolCandidateFilter (pools) -> or can we just deprecate+remove PoolCandiateFilter? ([♻️ Dead Code - Delete PoolCandidateFilterInput from the graphQL Schema #5193](https://github.com/GCTC-NTGC/gc-digital-talent/issues/5193)?)
> * Add field-level permissions to Skill type (experiences)
> * Use field-level permissions on inputs to combine updateUserAsUser and updateUserAsAdmin? (undecided on value of this)
> * Can we improve how we guard collections of items in the schema? [Discussion #6038](https://github.com/GCTC-NTGC/gc-digital-talent/discussions/6038)

@tristan-orourke Bump for 2024!

**Comment by tristan-orourke** [comment]
Looks like all of this is either already done, or no longer planned! I will close 😁
