### ISSUE TITLE
✍️ Update default minimum education requirement copy

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6598]
## 🌟 Details

@gobyrne has asked us to revise the default minimum education text so that it refers to _graduating_ instead of _completing_. He can elaborate on the why of this ask when he returns. I've provided an example below and will confirm final text with the relevant folks.

```
I meet the 2-year post-secondary option
Successful completion of two years of post-secondary education in...
```
becomes
```
I meet the 2-year post-secondary option
Graduation from a program of 2 years or more offered by a recognized post-secondary institution. The program must have a specialization in...
```

## 🗃️ Tasks

- [x] Confirm final English text with Lauren, Anne-Marie, and co.
- [x] Update Figma components/patterns to reflect the change
- [ ] Get translated text
- [ ] Get relevant links
  - [x] [EN - `recognized post-secondary institution`](https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html#rpsi) 
  - [ ] [FR - `???`](https://www.canada.ca/fr/secretariat-conseil-tresor/services/dotation/normes-qualification/centrale.html#eepr) 
- [ ] Update the copy in the codebase

## 📸 Screenshots

<details><summary>New form with updated content</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3365980d-5bdc-48ad-afae-c30e75d1ab18" />
</details>

## 💬 Feedback

<details><summary>@substrae and Anne-Marie's feedback (2023-05-18)</summary>
<br>
<p>It's unclear from the proposed text that the "2 years" is a minimum, so we've decided to alter the text to make it clearer:</p>
<pre><code>Graduation from a program of 2 years or more offered by a recognized post-secondary institution. The program must have a specialization in...</code></pre>
</details> 
<details><summary>Anne-Marie's feedback (2023-05-15)</summary>
<br>
<p>The standard uses the following text:</p>
<pre><code>Graduation from a two-year program of study from a recognized post-secondary institution with acceptable specialization in computer science, information technology, information management or another specialty relevant to the position to be staffed.</code></pre>
<pre><code>Réussite d'un programme d'études de deux ans, offert par un établissement d'enseignement postsecondaire reconnu, avec spécialisation acceptable en informatique, en technologies de l'information, en gestion de l'information ou dans une autre spécialité pertinente pour le poste à combler.</code></pre>
</details>

**Comment by tristan-orourke** [comment]
@yonikid15 if you haven't got the translations back for #6541 yet, you may want to send the new text off right away and resolve this in the same PR.
