### ISSUE TITLE
✍️ Update "Foreign Affairs" to "Global Affairs Canada" in our department list

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6642]
## 🌟 Details

GAC (Global Affairs Canada) has pointed out that they're being referred to as "Foreign Affairs" on our platform. I'm assuming this is the result of an outdated departmental list, but they've asked us to update their name: 

`Global Affairs Canada` | `Affaires mondiales Canada`

## 🗃️ Tasks

- [x] Get the latest name in both languages
- [ ] ~Update the departments model to reflect the correct name~
- [ ] Ensure any seeders are updated
- [ ] Ensure there's nowhere else this might have been hard coded

## 💬 Feedback

<details><summary>Note from @tristan-orourke (2023-05-18)</summary>
<p>Updating the name of the department must be done by platform admin users.</p>
</details>

**Comment by mnigh** [comment]
@substrae Global Affairs Canada is the applied title but Department of Foreign Affairs, Trade and Development is still the legal title. See: https://www.tbs-sct.canada.ca/ap/fip-pcim/reg-eng.asp

I believe we got the list of departments, which includes the department number and the legal titles of the departments and agencies: https://www.tpsgc-pwgsc.gc.ca/recgen//pceaf-gwcoa/2122/txt/rg-3-num-eng.html

So, if we are changing names like this, we should probably decide if we are changing them all to applied titles, not just one.

**Comment by substrae** [comment]
@mnigh @gobyrne 

I think we need to be using the applied title, given that that's the name a majority of users will understand. @gobyrne Feel free to step in here, but I'm not sure how we go about getting access to applied names in this situation. Worst case, we handle it on a case-by-case basis.

**Comment by petertgiles** [comment]
Decision from Gray: go ahead with issue as written
