### ISSUE TITLE
✨ Candidate profile updates (Part 1)

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#6731]
# ✨ Details

This issue is the first part of a series of updates to candidate profiles, along with a handful of other central UI component enhancements.

#### 🧩 Profile update epics
- #6731 
- #6930

# 🗃️ Requirements

```[tasklist]
## ⚙️ Central component updates
- [ ] #6729
- [ ] #6733 
- [ ] #6734 
- [ ] #6739
```

```[tasklist]
## 🗃️ General tasks
- [ ] Ensure directional language is addressed if found in the designs
- [ ] Ensure pronoun usage switches from "My" to "Your"
- [ ] Add `aria-label` to repeated items to better describe their individual actions
- [ ] Update all text to match the updated designs
- [ ] Update text of accordion triggers (sensitive to open/closed)
```

### Your dashboard ([Figma file](https://www.figma.com/file/jHsXzqMfBtomLa1Gom94Y7/Applicants---Dashboard?type=design&node-id=866-29701))

- [ ] Ensure the links in the page subtitle exist and link to/scroll to the appropriate pages/sections
- [ ] Simplify the dashboard hero cards and link relevant sections to their pages/sections
- [ ] DO NOT worry about the "Skills showcase" dashboard card just yet
- [x] #6738
- [ ] Allow for the unique alert contexts
  - [ ] Admittance into a new pool
  - [ ] First visit to the dashboard after applying to the IAP
  - [ ] First visit to the dashboard mid-application to the IAP

<details><summary>📸 Empty (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ee55532b-c290-44ea-8301-287e9d7503b1" />
</details>

<details><summary>📸 Empty (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d854e0c5-dd40-40fb-8bc8-9bcbae7b0030" />
</details>

<details><summary>📸 Completed (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/808bdcc8-d9a8-40d9-80ec-4f8007389e4e" />
</details>

<details><summary>📸 Completed (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3cb72606-33dd-4dff-97fb-8c8c446ce677" />
</details>

#### Unique alert situations

<details><summary>📸 New pool alert</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2680ba92-35ac-445a-8ed8-9929e0713e02" />
</details>

<details><summary>📸 Mid-IAP application alert</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/24e32f6c-e561-4448-87cd-06bded0c707e" />
</details>

<details><summary>📸 Post-IAP application alert</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/07abba0e-eee9-493f-987c-c1fcb7e86dc6" />
</details>

### Profile information ([Figma file](https://www.figma.com/file/UeTUDknj3s9ZgLCFF8eTcU/Applicants---Profile-V8?type=design&node-id=1-6308&t=BaxsgWiLRD7ouY9m-4))

- [ ] Copy the inline form functionality from the application and centralize it in both places ([Figma file](https://www.figma.com/file/2VF8cE4cctTBQUkPBcVxUG/3.-Patterns?type=design&node-id=412-36669))
- [ ] Update "read" view to be more consistently displayed in a grid
- [ ] Add the "Account and privacy" section
  - [ ] Add login and authentication expansion
  - [ ] Add functionality for managing recruitment inside the "Manage recruitment availability" expansion
  - [ ] DO NOT worry about account deletion for now

<details><summary>📸 Empty (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/a86dbca6-b52d-451c-ab09-87c97aa367ff" />
</details>

<details><summary>📸 Empty (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b0bd78f9-983a-4591-8592-984a4eaa506b" />
</details>

<details><summary>📸 Mid-edit (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/947d3a8a-e3aa-47d7-9956-c74cfff4a559" />
</details>

<details><summary>📸 Mid-edit (Collapsed)</summary> 
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/881a9fed-4bf2-401b-bba4-7484c1284293" />
</details>

<details><summary>📸 Completed (Expanded)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/6a2b0be9-a4ea-4283-a087-4e3c0b50b3b8" />
</details>

<details><summary>📸 Completed (Collapsed)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/54a97152-844b-4915-92c8-2739cee0590a" />
</details>

#### DEI updates

- [ ] Rework the DEI section content and collapse relevant information into an expansion
- [ ] Rework available DEI cards to show the definition by default
- [ ] Rework the DEI claim cards to show the new layout and affirmation
- [ ] Update the DEI dialogs to reflect new additions (see Indigenous identity, visible minorities)

Affirmation edge case

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c6aac9de-a8e0-4768-81e9-2697a2c67798)

DEI dialogs

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/f4409a5c-fe18-47e1-83a3-cd7ba47444e2)

### Résumé and talent pools ([Figma file](https://www.figma.com/file/UeTUDknj3s9ZgLCFF8eTcU/Applicants---Profile-V8?type=design&node-id=1-6398&t=BaxsgWiLRD7ouY9m-4))

- [x] #6735
- [ ] Migrate qualified recruitments to the résumé page
- [x] #6737
- [ ] Allow for the unique alert contexts
  - [ ] Admittance into a new pool

<details><summary>📸 Empty</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0f80d83c-6c60-435f-a6ca-9474c1f69a24" />
</details> 

<details><summary>📸 Completed</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/eca51d89-a409-4d34-bf3c-fb25a4f9641e" />
</details>

#### Unique alert situations

<details><summary>📸 New pool alert</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b68a9c46-5e8a-4ce9-9523-27886c5f279c" />
</details>

**Comment by mnigh** [comment]
12 of 12 Issues completed in this epic and part 2 of the related epic, **Candidate profile updates (Part 2)** #6930, has been closed.

@substrae can this also be closed as completed or do more issues need to added to the epic in zenhub?

**Comment by substrae** [comment]
@mnigh I think we can probably close this, yeah.
