### ISSUE TITLE
✨ Update the "Résumé and talent pools" page (previously Skills and Experience page)

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#6773]
## ✨ Feature

Change the "My experience and skills" page into the "Résumé and talent pools" page. This is a fairly significant redesign. See the figma files.

## 🎨 Design File

[Figma file](https://www.figma.com/file/UeTUDknj3s9ZgLCFF8eTcU/Applicants---Profile-V8?type=design&node-id=1-6398&t=BaxsgWiLRD7ouY9m-4)

## 📸 Screenshot

<details><summary>📸 Empty</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/0f80d83c-6c60-435f-a6ca-9474c1f69a24" />
</details> 

<details><summary>📸 Completed</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/eca51d89-a409-4d34-bf3c-fb25a4f9641e" />
</details>

## 🙋‍♀️ Proposed Implementation

(optional) Do you have a proposed implementation?

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Update title, subtitle and breadcrumbs
- [ ] Replace tabs with a single "Manage your resume" section
- [ ] Add a "Qualified recruitment processes" section, which shows the same ApplicantCards as the "past applications" section from #6771 
- [ ] "Qualified recruitment processes" has a link to Browse Jobs
- [ ] Experiences can be sorted by date (recent first) or by title (alphabetically) and can be filtered by type (work, education, etc, or All types)
- [ ] Qualified recruitments can be sorted by ??? (Ignore this for now)
- [ ] Uses the same experience card as #6735
- [ ] Uses the same ApplicationCard as worked on in #6747

**Comment by tristan-orourke** [comment]
@substrae Questions:
- Do the qualified recruitments need sort options? You don't have sort options on the Applicant Dashboard #6771.
- Should we port these experience sort/filter options back to the Application Resume page? Is that reflected in Figma yet?

**Comment by substrae** [comment]
@tristan-orourke 

1. If it's easier to go without, I think we can re-evaluate them and add them at a later date; the fact that they don't exist on the Applicant Dashboard is because those aren't recruitments, they're applications, which are a different mental model
2. Ideally the experience sort/filter changes should be moved to the application, yes

**Comment by tristan-orourke** [comment]
@substrae Hm, regarding recruitments vs applications, we're using the same component to display them on both pages, did you want something else?

**Comment by substrae** [comment]
@tristan-orourke 

From a data modelling perspective, they should be two different things to me, yes:
- One is the model for a pool/job
- One is the model for an application to a pool/job

**Comment by petertgiles** [comment]
Please update the links on the dashboard page as part of this issue as well.
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/97085f9b-bd3d-4e88-a73e-966d69c4e6f8)

**Comment by tristan-orourke** [comment]
Only applications with the following states should be considered Qualified Recruitments:

Status | Badge
--- | ---
QUALIFIED_AVAILABLE | Qualified
QUALIFIED_UNAVAILABLE | Qualified
QUALIFIED_WITHDREW | Qualified
PLACED_CASUAL | Qualified
PLACED_TERM | Qualified
PLACED_INDETERMINATE | Qualified
EXPIRED | Expired (in red)
