### ISSUE TITLE
⌨ Replace region multiselect with checklist

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#7073]
## ⌨ Accessibility Issue

Our multiselect component has many accessibility issues. While we work on these, we want to replace prominent uses with a checklist. This means the region input on the search page.

## 📸 Screenshot

![Screenshot 2023-06-22 092253](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/04aa74f6-0606-4498-b37d-9f8ec79c306f)

## 🙋‍♀️ Proposed Solution

Replace the `<Multiselect />` with a `<CheckList />`

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the issue was addressed.

- [ ] Region is now a checklist
- [ ] Form is still submitted with the same data
- [ ] No information is lost while submitting a request

**Comment by petertgiles** [comment]
@Jerryescandon Would you like to provide a design or should it be up to the dev?

**Comment by Jerryescandon** [comment]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/a405c1c0-bfd5-48ae-897b-0114e90d5944)
