### ISSUE TITLE
Search requests - manager title and supervisory fields

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7232]
## DESCRIPTION

Managers submitting requests keep putting their own job title in the field that is requesting the job title for the position they are trying to fill, to make this clear we are splitting the request form into two sections, "Contact information" and "Additional job details"

DCM Quote:
> Hey Jerbo! Not a big thing at all, but thought I would flag to you... I've noticed a few clients who are confused with this field on the request.. instead of putting the title of the role here, they often put their own title instead.. 

Also, DCM would like to know if the position in a request is a Team Lead or Individual Contributor type of position? to learn this we are adding a new required field to the form.

On the admin side:
Supervisory checked -> "Team lead"
Supervisory not checked -> "Individual contributor"

## TO-DO

1. Separate section into two: `Your contact information` and `Details about the job opportunity`
2. Move current field down to new section with the notes
3. Add a new field for the "Job title" for the person submitting the request
4. Add a new field to indicate a supervisory role

### Screenshots

<details><summary>Request form with new and moved job title fields</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/73b498ef-3d02-4c37-9c67-c57517f79ca4)

</p>
</details> 

<details><summary>Admin request page with new and moved job title fields</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/800d343f-f6bb-441a-8ab0-47ae817c0e0b)

</p>
</details> 

### Acceptance Criteria
- [ ] Database mutation to store new fields (supervisory role, position_type, to be an ENUM)
- [ ] Schema updated
- [ ] Request page with form updated
- [ ] Admin page updated

**Comment by vd1992** [comment]
Will definitely need to adjust field names to clarify things data model. 
What should be the term or name used to refer to request-submitters?

"Requesters"? So requester_job_title and so forth
"Talent seekers"? So talent_seeker_job_title and so forth

**Comment by petertgiles** [comment]
@Jerryescandon is the "Yes this is a superviosry position" checkbox out of scope for this issue?

**Comment by Jerryescandon** [comment]
> @Jerryescandon is the "Yes this is a superviosry position" checkbox out of scope for this issue?

Technically, but we also have an issue for that one in https://github.com/GCTC-NTGC/gc-digital-talent/issues/7008 , might be worth merging? 🤔

**Comment by gobyrne** [comment]
@Jerryescandon Is "additional job details" clear enough that it's about the talent request that they are submitting and not about their job? I just wanna be SUPER clear.

**Comment by gobyrne** [comment]
"Additional details about the position you are looking to fill" ? Maybe not that long...

**Comment by petertgiles** [comment]
On the admin side
Supervisory checked ->  "Team lead"
Supervisory not checked -> "Individual contributor"

Correct?

**Comment by Jerryescandon** [comment]
Do we need to add the new fields as columns to the 'Requests' table? I dont imagine the job title to add much, but the team lead vs Contributor might be valuable.

**Comment by petertgiles** [comment]
> Do we need to add the new fields as columns to the 'Requests' table? I dont imagine the job title to add much, but the team lead vs Contributor might be valuable.

Yeah, it should be covered by the AC "Database mutation to store new fields".
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/8978655/d3eb74de-598d-4181-a368-a9c107d884aa)
I imagine the dev will go with `manager_job_title` and `is_supervisory_role` or something like that.

Unless you think the "type of position" field might have more than two options in the future?

**Comment by vd1992** [comment]
@Jerryescandon 
Question, do the new fields in "Request information" have to go in that specific spot?
Currently the same component fills in these two bits, changing one will break parity and require two different components to serve different views.

Component `<SearchRequestFilters>` in `apps/web/src/components/SearchRequestFilters/SearchRequestFilters.tsx`

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/54551ed7-e346-47fd-865c-794b49d378aa)

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/2e8a2320-cf16-4c45-bc37-929549f044eb)

**Comment by Jerryescandon** [comment]
Interesting 🤔 
I guess we can maintain parity by moving the new things underneath, just above the notes. e.g:

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/59d4bcb1-b3f7-43e7-80aa-d817520de053)

**Comment by vd1992** [comment]
Thank you! 
I think this should work fine.

**Comment by vd1992** [comment]
One more question @Jerryescandon 
When there is no value for the new fields, position type and manager job title, what would you like the null state to read?

**Comment by vd1992** [comment]
Currently it defaults to the non selected text

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/40485260/ca0f5096-b5a1-4c4d-875c-764a3d2d985d)
