### ISSUE TITLE
Skill Library

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7377]
Allowing users to add skills directly to their profile without going through Experiences. Involves new UI along with changes to backend.
```[tasklist]
### Tasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/5060
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6932
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7392
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7394
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6936
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7378
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7386
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7388
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7387
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7380
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6942
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6989
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6956
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/6938
```

**Comment by gobyrne** [comment]
Moved last blocked-on-design issue to the cleanup epic. Closing!!!
