### ISSUE TITLE
✨ Skill showcase page

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7386]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c70cb2f2-ba21-4344-872b-718078c723a9)

## ✨ Feature

On this page users can define their "top skills" and "skills you'd like to improve". They can do this separately for Behavioral and Technical skills, for a total of 4 lists (for now). Each list will be orderable by the user.

## 🕵️ Details

You don't actually edit the lists on this page. This page displays all four lists, and has links to other pages where you edit each one specifically (#7388).

QUESTION: what should the url of this page be?
ANSWER: `/applicant/profile-and-applications/skills/showcase`

## 📸 Screenshots

For convenience only - remember to work from figma to stay up-to-date!

<details><summary>Full page (Incomplete)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5e7f2012-316c-4d29-b26a-5a7695d33e82" />
</details>

<details><summary>Full page (Complete)</summary>
<img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2de8f71d-5603-4f15-9863-06347036a0d9" />
</details>

## 🌎 Localization

(optional) Provide any new copy along with translations available.

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] This is behind SKILL_LIBRARY feature flag
- [ ] Page exists at a new route
- [ ] Page has correct breadcrumbs
- [ ] Table of contents, with two entries and a button-styled link to Skill library
- [ ] Both sections show two lists, one for each skill type
- [ ] Lists show skills in a specific order (determined when lists are edited)
- [ ] Edit buttons on each list go to #7388
- [ ] If a list is empty, null state is a link to #7388
- [ ] Lists show name of each skill as a link to #7378, and the user's skill level if present
- [ ] "Manage all skills" links point back to Skills library page
- [ ] new card component `ShowcaseCard` or variant of `Card` component (research needed to determine if `Card` component can be used on its own)
