### ISSUE TITLE
Removed status not intended to be shown to applicants

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7441]
## Description

The purpose of the "REMOVED" status is intended to be a cleanup tool for "retrofit-recruitments".

Applicants whose status has been placed as removed are meant to signify that they have now properly created a real account and placed on a pool accordingly. OR move users from old generic "catch-all" recruitments into more specific recruitments. 

DCM were only meant to tag these users as "REMOVED" to prevent them from showing up twice in request results as they were being properly transitioned from fake accounts and pools and into real accounts and pools.

Meaning "REMOVED" was never meant to be a status that was intended to be shown on the applicant facing side, since it's meant to remove duplicates.

## To-do

Ideally removed status should actually prevent any card from appearing on the applicant facing side. Applicants tagged as removed should all ideally been placed into another more appropriate pool.

We should HIDE all cards tagged as removed on the applicant facing side.

## Screenshots

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/e179c5fe-e452-429a-957b-0b296154d711)

## Acceptance Criteria
- [ ] Profile and applications checked
- [ ] Experiences page checked
- [ ] Profile page checked

**Comment by petertgiles** [comment]
@Jerryescandon This issue has the blocked:design label still but was added to Santa's list for next sprint.  Is this ready to be worked on?

**Comment by Jerryescandon** [comment]
I would like for @gobyrne to review this first and confirm with DCM, ideally also Lauren. It's one of those that are easy fixes with drastic impacts.
