### ISSUE TITLE
⛰ Skill Family updates

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7573]
We will be doing a big update on skills and skill families soon. Some skills, and most Skill Families, will be retired and replaced with new ones which are more closely tied to work streams.

We want to update the Skill Family and Skill models slightly to better represent relationships between Skills, Families, and Streams. We want to make sure that Platform Admins can edit and create these relationships on the admin platform. This update will be happening in September, so we want to have these updates done soon.

Question:
- What are Skill Families really for? 
  - Currently we use Skill Families to organize skills in the skill picke
- Then should the "templates" associating "core skills" and "commonly requested skills" with streams and substreams use a different grouping from Skill Families? 

```[tasklist]
### Tasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7574
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7576
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7575
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7672
- [ ] https://github.com/GCTC-NTGC/design-gc-digital-talent/issues/30
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/7674
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/13362
```

**Comment by mnigh** [comment]
@tristan-orourke did the remaining issues in this epic and specifically [this](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7574#issuecomment-1865159775) get discussed as part of the forward plan yet?

**Comment by mnigh** [comment]
@tristan-orourke is this epic still relevant or can it be closed as stale?

**Comment by mnigh** [comment]
> [@tristan-orourke](https://github.com/tristan-orourke) is this epic still relevant or can it be closed as stale?

@petertgiles same question, is this epic still relevant or can it be closed as stale?

**Comment by petertgiles** [comment]
Stale issue.  Most subissues are done and I converted the last item to an issue for separate consideration.
