### ISSUE TITLE
✨ Create `WorkStream` database entity based on `PoolStream` enum

### ISSUE THREAD

**Issue by tristan-orourke** [GCTC-NTGC/gc-digital-talent#7574]
## ✨ Feature

Create a Work Stream database model. Unlike our PoolStream enums, these models will be able to hold metadata, such as relationships to Skill Families.

## 🕵️ Details

The data model is
```
type WorkStream {
  id: ID!
  key: String
  name: LocalizedString
  plainLanguageName: LocalizedString
  community: Community
}
```

Other models which reference PoolStreams are
- Pool
- ApplicantFilter
- JobPosterTemplate

These models need to be updated to convert them to a relationship to WorkStream(s), and that data must be migrated in data in the database. Where we currently have logic which checks for certain PoolStream enums, we should be able to use the related community directly instead.

There are also the following query/mutation inputs that use PoolStream, which will need to be updated on the frontend and backend to use WorkStream id instead:
- PoolFilterInput
- ApplicantFIlterInput
- PoolCandidateSearchRequestInput
- CreateApplicantFilterInput

When changing ApplicantFIlterInput and PoolCandidateSearchRequestInput, we also need to make sure candidate search (ie scopeQualifiedStreams) still works.

## 🎨 Design File

Include a link to the design file (if it exists).

## Proposed Implementation

1. migration which adds work stream table and nullable work_stream_id foreign keys. Runs automatically during deployment.
2. manually run seeder which populates Work Streams table
3. manually run script which populates work stream relationships on pools, applicant_filters, and job_poster_templates tables, based on their poolStream values
4. #12142 

## 🌎 Localization

Use existing copy for workstream names.
Plain language names can be left null initially.

For communities: All workstream should be in Digital Community EXCEPT Access to information and privacy (which belongs in the community with that same name)

```[tasklist]
### Tasks
- [ ] Create model w/ migrations, seeders, policies
- [ ] Update process' to use new `WorkStream` model instead of `PoolStream` enum
- [ ] Update search requests and applicant filters to use new `WorkStream` model
- [ ] Remove old data related to `PoolStream`
```

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [x] WorkStream added to graphql schema
- [ ] Pool, ApplicantFilter, PoolFilter and JobPosterTemplate now refer to a WorkStream model instead of a PoolStream enum
  - [ ] After running migrations, these models workStream's match their previous enums
- [ ] GraphQL inputs which reference PoolEnum use WorkStream id instead
- [ ] Searching candidates by stream continues to work on Talent Search page and admin Candidate tables
- [ ] WorkStreams have a name (localizedString, non-nullable), a plainLanguageName(localizedString, nullable), a key field (non-nullable, populated with existing enum) and a relationship to a Community (non-nullable).
- [ ] Seeding creates the real set of work streams if they don't exist yet. WorkStream seeder is safe to run on Prod.
- [ ] Pools are seeded with full WorkStreams now
- [ ] A query exists which returns all WorkStreams
- [ ] Mutations exist to creates and edit a WorkStream. Protected by a new PlatformAdmin-only permission.

**Comment by tristan-orourke** [comment]
Question for Lauren: will adding a work stream continue to be a very rare thing? Do Platform Admins need to be able to create them on the platform, or should adding streams remain a dev task? What about editing the metadata - they could be editable on the platform but not creatable?

**Comment by mnigh** [comment]
@tristan-orourke what is the remaining question from the **blocked: question** label?

**Comment by tristan-orourke** [comment]
@mnigh this whole thing is up in the air. There was motivated by something which may or may not be on the forward plan anymore, pending some discussions about the forward plan which need to happen in the new year.

**Comment by mnigh** [comment]
> @mnigh this whole thing is up in the air. There was motivated by something which may or may not be on the forward plan anymore, pending some discussions about the forward plan which need to happen in the new year.
> 
> That applies to the whole `Skill Family updates` epic.

@tristan-orourke is this on the forward plan for 2024?

**Comment by tristan-orourke** [comment]
![Talent Management Data Model](https://github.com/user-attachments/assets/779a5089-728d-4bf8-ba5d-a7b91b262aa2)

**Comment by tristan-orourke** [comment]
Want to discuss migration plan in refinement

**Comment by esizer** [comment]
> * Write a second migration which creates WorkStream rows for each of our stream enums.
> * Write a third migration (or continue the second one?) to replace `pools.pool_stream` with `pools.work_stream_id`, making sure each pool has the correct foreign id, and the same for ApplicantFilter, PoolFilter and JobPosterTemplate.

These last two seem like they may not work well as migrations 🤔 I feel like the creation of the work streams should be a seeder and then the update of existing data be a script maybe?

**Comment by tristan-orourke** [comment]
Yeah, creating items in a migration feels wrong, but is possible, and I thought might be simpler in practice than the alternative.

I think the alternative process would be:
0. Code changes which deprecate poolStream or remove it from schema, even though it will remain in the database for now.
1. migration which adds work stream table and nullable work_stream_id foreign keys. Runs automatically during deployment.
2. manually run seeder which populates Work Streams table
3. manually run script which populates work stream relationships on pools, applicant_filters, and job_poster_templates tables, based on their poolStream values
4. After these confirmed to have run in production, create a new migration which removes poolStreams from the database and makes work_stream_id non-nullable on job_poster_templates. This will run automatically in a later deployment. 

If you prefer this approach give this comment a 👍

**Comment by mnigh** [comment]
@esizer does this issue still need the [blocked](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7574#event-15467609733) label?

**Comment by esizer** [comment]
> @esizer does this issue still need the [blocked](https://github.com/GCTC-NTGC/gc-digital-talent/issues/7574#event-15467609733) label?

Yup, it is blocked on some other tickets. Mainly:

- https://github.com/GCTC-NTGC/gc-digital-talent/pull/12152
- https://github.com/GCTC-NTGC/gc-digital-talent/issues/12151
