### ISSUE TITLE
✨ "Pool information" page redesign to "Process information"

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#7913]
## ✨ Feature

The pool information page which previously acted as a mostly static view of a single pool is being converted to a new page with cards and actions.

## 🕵️ Details

There are a few things that can't be fully completed right away and will be pushed off to a later issue.

- New look-and-feel for header and subnav are out of scope.  Use current theme as-is for new navigation elements.
- "pool is complete validation" coming later in  #7921

## 🎨 Design File

[Link to the design file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=5599%3A29295&mode=design&t=2lJASOC5nDFLR7Cp-1)

### 🧑‍🎨 Designer

@Jerryescandon 

## To-do

<details><summary> 📷 OLD "Pool information" page</summary>
<p>

![uat-talentcloud tbs-sct gc ca_en_admin_pools_a6b18dd9-476c-47e3-bf25-1dd95973d0ba](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/b080878e-03fc-40ed-9e7e-bf7c6f996865)

</p>
</details> 
<details><summary> 📷 NEW "Process information" page</summary>
<p>

![Frame 40](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/56bc0834-e89a-48b2-a345-d43643b412ab)

</p>
</details> 
     
1. Remove all static job poster information
2. Remove copy link button
3. New title and description
4. Create 3 new card sections:
     5. Advertisement information
     6. Assessment plan - only placeholder with "Coming soon" message
     7. Recruitment status

<details><summary>✨ Advertisement information card</summary>
<p>

### Advertisement information

1. Includes 2 action links: Edit advertisement and Preview poster
2. Edit advertisement navigates to "Advertisement information" (previously 'Edit pool')
3. Preview poster navigates to public poster version (currently called 'View pool advertisement')
4. It has 3 possible states depending on the information collected and whether or not it has been submitted

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/d1efdb12-771d-4701-97e8-dbbad917920f)

</p>
</details> 

<details><summary>✨ Assessment plan card</summary>
<p>

### Assessment plan

~1. Includes 1 action links: Edit assessment plan~ Create a placeholder only.  Assessment plan functionality will come later.

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/d1efdb12-771d-4701-97e8-dbbad917920f)

</p>
</details> 

<details><summary>✨ Process status card</summary>
<p>

### Process status

1. Includes Various links: 
     2. Submit for publishing OR Extend closing date
     3. Duplicate process
     4. Delete process OR Archive process.
5. Submit for publishing should trigger a modal confirmation
6. Extend closing date works like the current one (currently inside 'Edit pool')
7. Duplicate process works like the current one (currently inside 'Edit pool')
8. Delete / Archive process should work like the current one (currently inside 'Edit pool')
9. Publish this process is only available to Admins and it works like the current one (currently inside 'Edit pool')

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/a262f78d-b946-49ef-b6ab-b18282017579)

</p>
</details> 

<details><summary>Submit for publishing dialog</summary>
<p>

![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/16977254/14724761-9469-483e-850e-94a567167e6a)
User hardcoded DCM mailto link for now.

</p>
</details> 

## ✅ Acceptance Criteria

- [ ] Updated page matches Figma design
- [ ] Action links only appear to users with appropriate role
- [ ] Design review with designer

**Comment by vd1992** [comment]
Spin off issues (TODO)
- pool completeness variable
