### ISSUE TITLE
⚙️ Assessment Step Tracker

### ISSUE THREAD

**Issue by brindasasi** [GCTC-NTGC/gc-digital-talent#8454]
## ⚙️ Summary
 This component is used to track the candidates by assessment step wise. 

## 🎨 Design File
[Figma file](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Pools---Record-of-Decision?type=design&node-id=6872%3A37861&mode=design&t=JWMUVFyhTv34zHii-1) by @Jerryescandon 

> [!NOTE]  
> For all layout and spacing guidance, including how this component should respond on smaller devices, please see the Figma file.

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOWEvQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--5652fa4530bae2d4a2e4efdbb5bb772614503b80/image.png)

### ✅ Design checklist

- [ ] Default component
- [ ] Dark mode component
- [ ] Component variants
- [ ] Dark mode component variants (if applicable)
- [ ] Foundational design info (e.g. color info, icons, helpful values)
- [ ] Mobile (`base` query) layout and space diagram
- [ ] Desktop (`p-tablet` query or larger) layout and space diagram
- [ ] Accessibility considerations
- [ ] Hover states (if applicable)
- [ ] Dark mode hover states (if applicable)
- [ ] Focus states (if applicable)
- [ ] Dark mode focus states (if applicable)

### ✅ Accessibility checklist

- [ ] Tap targets are adequate on smaller screens
- [ ] Color contrast for all modes and states has been checked and cleared
- [ ] Zoom has been considered as layout changes occur
- [ ] `alt` text has been identified and labelled
- [ ] Non-standard states or interactions have been described and provided accessible design context

## A/C 

1. Null state - distrubution summary shows up as count 0 
2. Card has max height and when it reaches the candidate section get the scroll bar. Distribution block should be frozen on the top. 
3. Each candidate is linked to screening page and opens up the corresponding step in the accordion 
4. Candidate Assessment step status is shown as icons on the right 
5. Candidate priority is shown as icons on the right
6. Ignore book marks for now 
7. Sorting 

Main ordering (first on top):
 To Assess
 Successful/Screened in
 Unsuccessful/Screened out
Within those groups ordering:
 Priority entitlement (determined from their profile)
 Veterans (determined from their profile)
 Everyone else
And alphabetical within those groups (edited) 
8. Distribution Summary section  for Application step has Screened In, Screened Out status where as all other steps have Successful & Unsuccessful status

**Comment by mnigh** [comment]
@brindasasi aren't design issues meant to for the design repo? https://github.com/GCTC-NTGC/design-gc-digital-talent/issues. wondering why we need the `design` and `updates in progress` labels?
