### ISSUE TITLE
Incremental graphql codegen `client-preset` adoption

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#8681]
## ♻️ Debt/Refactor

We are migrating away from the deprecated `@graphql-codegen/typescript-urql` plugin to the `@graphql-codegen/client-preset` preset.

## 🕵️ Details

We are doing this for one main reason, [the developer recommends it](https://the-guild.dev/graphql/codegen/plugins/typescript/typescript-urql#:~:text=We%20now%20recommend%20using%20the%20client%2Dpreset%20package%20for%20a%20better%20developer%20experience%20and%20smaller%20impact%20on%20bundle%20size.) and we agree (I think).
```[tasklist]
### Tasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8720
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8719
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8716
```

**Comment by mnigh** [comment]
@tristan-orourke can this issue be closed now that the issues related to this epic are complete or did you have another process for epics for github projects?

**Comment by esizer** [comment]
This work has been completed.
