### ISSUE TITLE
✨ Update the job ad admin creation form

### ISSUE THREAD

**Issue by substrae** [GCTC-NTGC/gc-digital-talent#8751]
![image](https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/9ba3968a-af42-4d3e-90e9-2caaab4bccad)

## ✨ Summary

[Visit the Figma file](https://www.figma.com/file/e2DTvyppj41m6slFWTDZ0U/Admin---Job-advertisement-creation?type=design&node-id=52-40341&mode=design&t=niiYWsXhwxDFAFrP-0) • Contact @substrae with design questions

Due to the design updates on the job advertisement page (see #8657), the advertisement creation form has been updated to reflect the new information architecture and fields. While a majority of these changes are layout/styling related, there are a handful of new elements and functionality.

## 🎟️ Related issues

* #8657 
* #8752 

## ✅ Requirements

```[tasklist]
### General page changes
- [ ] Update the table of contents to reflect the modified page sections
- [ ] Ensure the table of contents component supports an `optional` state (always secondary color, aria label "Optional")
- [ ] Edit links use hidden text "Edit {section name}"
- [ ] Missing fields should use the same style error states as current (red text)
- [ ] side-by-side items should switch to stacked view with narrow views (probably at laptop width)
- [ ] Use a new feature flag to route to a new component representing the updated Job Poster creation page
```

Feel free to ignore header/breadcrumb/menu differences for this ticket.

<details>
  <summary>📸 Full page screenshot (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2ffd8a99-bfcc-4687-8180-711d40df7896" />
</details> 

<details>
  <summary>📸 Full page screenshot (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7668410e-ffd5-4c09-a3d3-5cb0d26555f0" />
</details> 

<details>
  <summary>📸 Full page screenshot (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/418c927e-c38e-450a-9e95-2f3ea36e0c71" />
</details> 

<details>
  <summary>📸 Table of contents comparison</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/18d1a991-5672-4a25-a319-cbe850fd58cf" />
</details> 

```[tasklist]
### Basic information changes
- [ ] Update the section title and add new instructional text
- [ ] Separate fields into 2 sections: _Advertisement details_ and _Closing date_
- [ ] Ensure instructional text is updated for both sections
- [ ] Specific title field renamed to Job title
- [ ] ~Add the _Length of opportunity_ field with the options provided (see below)~ #8824
- [ ] Add the _Closing date_ example dialog with the copy provided
- [ ] Update the default null state for _Advertisement details_ so that it shows on page load but retains the selections made on the _Getting started_ page (e.g. classification) in the editable format
- [ ] Update styles to match
```

* Note that the empty states shown below need updating, because by default, the page shows a bunch of "Not provided" fields due to the previous page asking about classification. I'm hoping to avoid this by showing a null state instead, with their previous selections for classification and other fields applied to the "Editable" view instead.

<details>
  <summary>📸 Basic information comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bb8aee44-0a87-4a1b-8f20-77c2687d4d46" />
</details>

<details>
  <summary>📸 Basic information comparison (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2adf5843-55a4-4da3-a21d-e4c83ab490f2" />
</details>

<details>
  <summary>📸 Basic information comparison (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/86c15052-bbf5-4ace-8d20-45c88e98223d" />
</details>

#### Length of opportunity

Out of scope for now (#8824)

~This new field should be a `<select>` and have the following `<options>`:~
~* Term (6 months)~
~* Term (1 year)~
~* Term (2 year)~
~* Indeterminate (Permanent)~
~* Various~

#### Dialogs

<details>
  <summary>📸 Closing date example dialog</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/3b9c6c6c-9f7f-4142-af04-ff779402ffe3" />
</details> 

```[tasklist]
### Core requirements changes
- [ ] Update the section title and add new instructional text
- [ ] Update styles to match
```

<details>
  <summary>📸 Core requirements comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/39f96be1-d3c6-4a93-9de3-6265219eadb0" />
</details>

<details>
  <summary>📸 Core requirements comparison (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/161b7de5-18f0-4bb3-bbfd-66d430b4d327" />
</details>

<details>
  <summary>📸 Core requirements comparison (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7adf2611-958b-4aaf-b0e7-1fd27552b19f" />
</details>

```[tasklist]
### Special note changes
- [ ] Update the section title and add new instructional text
- [ ] Ensure this section uses the `optional` state as it's not required for submission
- [ ] Move the section up the page to match the design
- [ ] Ensure the field has the appropriate word limits in English (100) and French (130)
- [ ] Update styles to match
``` 

<details>
  <summary>📸 Special note comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/55d1e5d2-5138-4d6a-8f3d-3ee72eddbad8" />
</details>

<details>
  <summary>📸 Special note comparison (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/fb13331d-2ee3-4fb0-b27a-c12b2ce71d71" />
</details>

<details>
  <summary>📸 Special note comparison (Editable, confirmed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5fad67b2-ac88-48ed-9bef-cb9e2f16e53c" />
</details>

<details>
  <summary>📸 Special note comparison (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/7a4cc4be-dbce-4daf-9c80-6e074c5889d7" />
</details>

```[tasklist]
### Minimum education changes
- [ ] Update the section title and add new instructional text
- [ ] Ensure the layout accommodates the variants of 1, 2, and 3 requirements
- [ ] Update styles to match
- [ ] New Qualification Standards link URL: https://www.canada.ca/en/treasury-board-secretariat/services/staffing/qualification-standards/core.html
```

<details>
  <summary>📸 Minimum education comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/512e1739-e220-45e8-9e77-2d566a20f924" />
</details>

#### Count variants

<details>
  <summary>📸 1 requirement</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/ee90eaf2-c3fd-4e2d-b258-4bb63bf64409" /> 
</details>

<details>
  <summary>📸 2 requirements</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/cb84d402-9d5e-4538-af9b-13f0b722ab38" />
</details>

<details>
  <summary>📸 3 requirements</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/feeda591-1e97-40c5-8c8a-1fc05f8833c7" />
</details>

```[tasklist]
### Skill requirements
- [ ] Update the section title and add new instructional text
- [ ] Bring essential and asset skill sections in as subsections
- [ ] Update essential and asset titles and instructional text
- [ ] Ensure the asset criteria section uses the `optional` state as it's not required for submission
- [ ] Update the table layout (pay particular attention to the actions column)
- [ ] ~Update the _Add a new skill_ dialog to offer level selection~ -> #8828
- [ ] Update styles to match
- [ ] aria labels for action skill "Edit skill , {skill name}" and "Remove skill , {skill name}" like before
```

<details>
  <summary>📸 Skill requirements comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/d4501433-afd1-4084-87e4-50ca9ed31421" />
</details>

<details>
  <summary>📸 Skill requirements comparison (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/8b39b699-97aa-48e0-8e6c-24b5ca03578a" />
</details>

#### Dialogs

<details>
  <summary>📸 Add a skill dialog (Initial)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2840730a-4c86-4d7a-9799-7a0fdf39adf5" />
</details>

<details>
  <summary>📸 Add a skill dialog (Selected)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/b0480379-5eab-4a58-8b4a-1601a1237420" />
</details>

```[tasklist]
### About this role changes
- [ ] Update the section title and add new instructional text
- [ ] Bring the _Impact statement_ and _Work tasks_ sections into this one as subsections
- [ ] ~Add the new, `optional`, _About us_ section~ -> #8829
- [ ] Update all subsection titles and their respective instructional text
- [ ] Add or update the word count for _Impact statement_ in English (150) and French(195)
- [ ] Add or update the word count for _Work tasks_ in English (150) and French(195)
- [ ] ~Add or update the word count for _About us_ in English (100) and French(130)~ #8829
- [ ] ~Ensure _About us_ is using the `optional` state as it's not required for submission!~ #8829
- [ ] Update styles to match
```

Rather than doing a comparison, this section consolidates the _Impact statement_ and _Work tasks_ sections with a new _About us_ question.

<details>
  <summary>📸 Full section (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e199ddfb-f834-42c4-9261-2230a755d286" />
</details>

<details>
  <summary>📸 Full section (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2357fd1d-856a-41fd-bf9a-dd423ece6579" />
</details>

<details>
  <summary>📸 Full section (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/e1fbb3aa-ea2f-44cb-a68f-9f01f4929c97" />
</details>

```[tasklist]
### Common questions changes
- [ ] Update the section title and add new instructional text
- [ ] ~Create a new `required` question called _Understanding classification_ that provides hard-coded, classification-specific descriptions~ -> #8831
- [ ] ~In instances where a classification's level is high enough for managerial roles (IT-03 thru IT-05), allow the user to select from descriptions for _Team lead_, _Advisor_, or _Both_, which then provides the relevant text~ #8831
- [ ] Bring _What to expect after you apply_ into this section as a subsection and update it's title and instructions
- [ ] ~Add a new `optional` question called _What to expect post-admission_ that allows for rich text input~ -> #8829
- [ ] Update styles to match
```

<details>
  <summary>📸 Full section (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/2e0706f5-902c-4c22-95ff-00ab2b123aa4" />
</details>

<details>
  <summary>📸 Full section (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/de2fb37b-b0a2-4b69-b846-898bad91ba18" />
</details>

<details>
  <summary>📸 Full section (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/5e621652-a7c1-40ab-8c75-76492e1950b1" />
</details>

#### Existing questions comparisons

<details>
  <summary>📸 What to expect post-application comparison (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/bdc4f225-41b0-472e-aaf6-a2aa16876c81" />
</details>

<details>
  <summary>📸 What to expect post-application comparison (Editable)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/98eb3a4d-3b76-47ce-b716-ba6435a390e0" />
</details>

<details>
  <summary>📸 What to expect post-application comparison (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/83eaaab0-92a0-4ef0-b39a-2d5c7a41fcc2" />
</details>

```[tasklist]
### General questions changes
- [ ] Update the section title and add new instructional text
- [ ] ~Modify the interaction so that form entry happens and saves through a dialog (this should help remove the need for the warning telling users to remember to save)~ -> #8832 
- [ ] Update the empty / completed states based on the new interaction
- [ ] Update styles to match
```

* ~Note that because screening questions are in flux thanks to RoD, this design might need further discussion when the time comes to build it. We might bring the behaviours over to the new _Additional questions_ section.~

* Note that screening questions have now been moved to the RoD UI, so this section has been updated to reflect the new "General questions" functionality.

<details>
  <summary>📸 General questions (Empty)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/90a44610-bbe0-436d-bb44-bc9870834dec" />
</details>

<details>
  <summary>📸 General questions (Completed)</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/befe63ab-0d97-4bab-9dc3-51466c35be4f" />
</details>

#### Dialogs

<details>
  <summary>📸 Add / edit a question dialog</summary>
  <img src="https://github.com/GCTC-NTGC/gc-digital-talent/assets/6960386/c0e172f7-5800-49d1-86d8-8fa427335adc" />
</details>

**Comment by tristan-orourke** [comment]
Can we consider how changes to screening questions (#8676) will be reflected in job poster creation?

**Comment by substrae** [comment]
@tristan-orourke I chatted with @petertgiles about this already - I also noted in the ticket for that particular update that the dev who plans to work on it should chat with us when the time comes, because it will depend on when the RoD and advertisement changes happen.

**Comment by substrae** [comment]
@petertgiles Just a heads up that Jerbo and I have discussed and updated the screening questions vs. general questions conflict. The issue body now represents the path forward. Gimme a shout if you need any clarity :)

**Comment by tristan-orourke** [comment]
Thanks @substrae! 

ps Just a quick note, the table of contents in figma and the screenshots still reads "Screening questions" instead of "General questions".

**Comment by substrae** [comment]
@tristan-orourke Doh! Thanks for catching that!
