### ISSUE TITLE
[EPIC] Update the job advertisement

### ISSUE THREAD

**Issue by gobyrne** [GCTC-NTGC/gc-digital-talent#8971]
Grouping all the job ad issues
```[tasklist]
### Tasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8828
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8824
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8657
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/8751
```
