### ISSUE TITLE
✨ Update `SearchResultCard`

### ISSUE THREAD

**Issue by esizer** [GCTC-NTGC/gc-digital-talent#9089]
## ✨ Feature

Split off from #9075

Updates to the search result cards that appear on the talent search page.

## 🕵️ Details

This includes minor tweaks to the layout/design.

```[tasklist]
### Tasks
- [ ] Move estimated candidates next to team, bold, secondary and copy change
- [ ] Remove bold from essential skills
- [ ] Convert essential skills from pills to bullet separated list
- [ ] Add `Separator` between copy and actions
- [ ] Convert request button to link style (keep as a functional button)
- [ ] Update request button copy
```

## 🎨 Design File

[Talent Search](https://www.figma.com/file/9V8kBIWxOXRaN9dkcVCU1o/Manager---Talent-search?type=design&node-id=0-1&mode=design&t=VnmcyAQhFftDxvVO-0url)

### 🧑‍🎨 Designer

@Jerryescandon

## 📸 Screenshot

![298981372-279e1f38-d5fb-4bf7-be25-1e48eb28e7ff](https://github.com/GCTC-NTGC/gc-digital-talent/assets/4127998/a97c1a3b-e5fc-403f-95ef-468aa9723c66)

## ✅ Acceptance Criteria

A set of assumptions which, when tested, verify that the feature was properly implemented.

- [ ] Cards updated to match design
- [ ] No functionality changes
