### ISSUE TITLE
Add all print options to "Print" button on candidate application page

### ISSUE THREAD

**Issue by Jerryescandon** [GCTC-NTGC/gc-digital-talent#9201]
## Description

Pool operators working on applications would like to be able to access all possible printing options available. They currently only have access to "Print application" but would like to have access to "Print full profile" and "Print profile without contact information" from the same action menu.

## Caveats

Depending on when this gets tackled (before or after RoD flag) there could be two ways to approach this since the application page would look different.

### Fix pre RoD flag

<details><summary>Show steps</summary>
<p>

### To-do

Add the options from the User profile print button to the application print button so we have a total of 3 available print options:

- Print application
- Print full profile
- Print profile without contact information.

<details><summary>📸 Application Print button</summary>
<p>

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/66dda0a6-6e52-4b39-96f1-a21478062401)

</p>
</details> 

<details><summary>📸 User profile Print options</summary>
<p>

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/f9a36179-e3a2-48d8-a582-db4836d4ae9a)

</p>
</details> 

</p>
</details> 

### Fix post RoD flag

<details><summary>Show steps</summary>
<p>

### To-do

Add a new in-line action menu in the "More actions" sidebar to include all three print options

<details><summary>📸 Application page with new print options</summary>
<p>

![image](https://github.com/GCTC-NTGC/design-gc-digital-talent/assets/16977254/5a12ef28-2456-45df-b29f-99be2d0d4a45)

</p>
</details> 

</p>
</details> 

## Design

[Figma link](https://www.figma.com/file/em5ArPr044YaIe1Vb1zCZz/Admin---Processes%2FPools%2FRecruitments---Record-of-Decision?type=design&node-id=8165%3A22212&mode=design&t=gnehnBHXJcHwPWEI-1) by @Jerryescandon 

## ☑️ Acceptance Criteria

- [ ] Functional Print user profile button added to pre-RoD candidate page
- [ ] Functional print buttons added to post-RoD candidate page
- [ ] Double check that this works without error for any Role who can see the Application
