### ISSUE TITLE
⛰️ [Epic] Server-Side Report Generation

### ISSUE THREAD

**Issue by petertgiles** [GCTC-NTGC/gc-digital-talent#9683]
```[tasklist]
### Subtasks
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9684
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9685
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9686
- [ ] #9893 
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9687
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9688
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9690
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9692
- [ ] https://github.com/GCTC-NTGC/gc-digital-talent/issues/9693
```

**Comment by tristan-orourke** [comment]
All subtasks for this are complete!
